name: Run Playwright test upon push to master branch

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright
    
    - name: Ensure browsers are installed
      run: python -m playwright install chromium --with-deps
    
    - name: Run tests
      run: pytest --screenshot=retain-on-failure --output=./test-results
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/